### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by edward-peters** [kometenstaub/csv-to-md#10]
Thank you for sharing this. I really need this functionality, but when I run the python script I get this:

```
File "csv_to_md-file.py", line 17
    self.settings:dict = {}
                 ^
SyntaxError: invalid syntax
```

Can you advise me what to do please?

**Comment by kometenstaub** [comment]
Make sure to use an up-to-date Python version. (See the Readme, I tested it on 3.9.4, the package that causes the issue is supported since 3.5)

**Comment by edward-peters** [comment]
Thank you so much for responding. Not being a programmer, it never occurred to me to check the version. I have now got your script working perfectly for my needs. Very grateful indeed for it and for your support. All best wishes. Edward
