### ISSUE TITLE
The setting isn't saved automatically

### ISSUE THREAD

**Issue by ooker777** [kometenstaub/csv-to-md#11]
I suppose that before the script exits it should save the current setting into saved_settings.py? It doesn't do that in my case. Also, there is no log as well

**Comment by kometenstaub** [comment]
There is an option to save it. If that doesn't work, I'd need more info.

**Comment by ooker777** [comment]
the option appears in what step? I don't see it

**Comment by kometenstaub** [comment]
It is only shown when you enter new settings. Record a gif and post it here, then we'll see whether it asks you to save them or not.

**Comment by ooker777** [comment]
![](https://i.imgur.com/iMIKbbY.gif)
I see that in your gif the option is prompted when everything is finished. This doesn't so in my gif

**Comment by kometenstaub** [comment]
It does, third line from the bottom. You answered with `N`.

**Comment by ooker777** [comment]
My bad 😞
