### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by viharm** [kometenstaub/csv-to-md#18]
Hi @kometenstaub , sorry to post an issue, here, but I couldn't find any other way to contact you. Just wanted to thank you for your effort in creating this. Although I didn't make full use of this, it did help me to import a bunch of items into Joplin from a CSV file that I had created to import the list into Todoist (but then changed my mind, and wanted to send them to Joplin instead). If it wasn't for this tool, I would have had to create those notes manually. Thanks.

**Comment by kometenstaub** [comment]
You’re welcome.
