### ISSUE TITLE
Suggestion - Support having the first x columns in YAML, the rest outside YAML

### ISSUE THREAD

**Issue by S-Wil** [kometenstaub/csv-to-md#7]
I would like to have a mix of fields inside and outside YAML, for example:

Input only 2 columns in YAML:
alias | tags | Name | Location

---
alias: [alias]
tags: [tag]
---
Name:: name
Location:: location

If you want them in both then just duplicate a column.

Another approach would be to include YAML in the column name, eg:
alias (yaml) | tags (yaml) | Name | Location

**Comment by kometenstaub** [comment]
This sounds interesting, but would involve making the script more complex and is not something I currently have time for.

**Comment by S-Wil** [comment]
I'm not a coder but I have a feeling I am going to teach myself a bit of Python as my use case is a little different.  Thanks for all the work you have done here.  Cheers.
