### ISSUE TITLE
Suggestion - import and export for mass editing and analytics

### ISSUE THREAD

**Issue by S-Wil** [kometenstaub/csv-to-md#9]
It would be great to be able to export a folder of notes from within Obsidian into a CSV so they can be edited on mass or used for analytics within CSV apps, eg. Google sheets and Excel.  If used for editing then consideration would have to be given to maintaining consistency (round tripping) through export and re-import.  I would value this highly.

**Comment by kometenstaub** [comment]
As said in #6, this is a batch import tool. It is not supposed to export markdown to CSV files.

I also don't see a way how one would make a tool to do it the other way round. One could of course export every line in a markdown file to a column in a CSV file, each row a different markdown file, but I don't really see how one would gain insights/value from that.

Mass editing of markdown files can already be done with (Regex) search and replace.

**Comment by S-Wil** [comment]
Appreciate this is not your focus but it's not just about regex work.  CSVs can be used for analytics much more readily than tools like Dataview.  The other main benefit is that exporting to CSV means you can merge external data (eg. export a set of markdown notes into CSV, merge an external data source into that CSV (dedup, cleanse, etc) and re-import it back into markdown).  This is something I'm wanting to solve for.  Cheers
